lrs/routes/web.php
<?php

/* 
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//mail layouts
Route::get('/mailLayout', function () {
    return view('admin.mailContent');
});
Route::get('/', function () {
    return view('welcome');
});
//email content edit

Route::post('/mailContentUpdate', 'ProductController@mailContentUpdate');
//
Route::get('/mailEdit', 'ProductController@mailContentEdit')->name('mailEdit');
//login
Route::get('/user/{url}', function ($url) {
    $url = $url;
    return view('user.login',compact('url'));
})->name('home');

Route::get('/user_admin/{url}', function ($url) {
    $url = $url;
    return view('admin.login',compact('url'));
})->name('user_admin');
 
Route::get('mail', 'webAdminController@mail')->name('mail');
Route::post('webLogin', 'webController@webLogin')->name('login');
Route::post('adminLogin', 'webAdminController@adminLogin')->name('adminLogin');
//navigate
Route::get('/navigation/{navigate}/{uid}/{app_url}/{company}', 'webController@navigation')->name('navigation');
//device
Route::get('removeDevice/{device}', 'webController@removeDevice')->name('removeDevice');
//homeadmin
Route::get('/option/{app_url}', 'webAdminController@admimHome');
//
Route::post('changePassword', 'webController@changePassword')->name('changePassword');
Route::post('changePicture', 'webController@changePicture')->name('changePicture');

//create
Route::post('/userRegister', 'userController@userRegister');
Route::post('/actionList/{app_url}', 'scanActionListController@actionList');
//////crud
Route::resource('products', 'ProductController');
Route::resource('action','ActionController');
////excel
Route::get('export/{app_url}', 'ExcelController@export')->name('export');
Route::get('exportVisitorData/{app_url}', 'ExcelController@exportVisitorData')->name('exportVisitorData');
Route::get('importExportView', 'ExcelController@importExportView')->name('importExportView');
Route::get('importExhibitor', 'ExcelController@importExhibitor')->name('importExhibitor');
Route::post('import/{app_url}', 'ExcelController@import')->name('import');
Route::post('importE/{app_url}', 'ExcelController@importE')->name('importE');

////exhibitorsView
Route::get('exhibitorsView/{app_url}', 'ExcelController@exhibitorsView')->name('exhibitorsView');
// proIndex
Route::get('proIndex/{app_url}', 'ProductController@index')->name('proIndex');
//event
Route::get('event', 'appController@viewAll')->name('viewAll');
//admin
Route::get('/create', function () {
    return view('admin.create_app');
})->name('create');
//expired
Route::post('expired/{id}', 'appController@expired')->name('expired');
//edit view
Route::post('editEventView/{id}', 'appController@editEventView')->name('editEventView');
//edit
Route::post('editEvent/{id}', 'appController@editEvent')->name('editEvent');

lrs/app/Http/Controllers/ActionController.php
<?php
  
namespace App\Http\Controllers;
  
use App\Product;
use App\ScanActionList;
use Illuminate\Http\Request;
use Alert;

  
class ActionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    { 
        $app_url = base64_decode($request->app_url);
        $products = ScanActionList::where('app_url',$app_url)->paginate(10);
        // return $products;
        return view('action.index',compact('products','app_url'))
            ->with('i', (request()->input('page', 1) - 1) * 10)->with('app_url',$app_url);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $app_url = base64_decode($request->app_url);
        return view('action.create',compact('app_url'));
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
  
        Product::create($request->all());
            
        return redirect()->route('action.index')
                        ->with('success','Product created successfully.');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('action.show',compact('product'));
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($request,Product $product)
    {
        $data = ScanActionList::where('id',base64_decode($request))->get();

        $product = $data[0];
        

        return view('action.edit',compact('product'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {

        $request->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
  
        $product->update($request->all());
  
        return redirect()->route('action.index')
                        ->with('success','Product updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */ 
    public function destroy(Request $request,Product $product)
    {
        ScanActionList::where('id',$request->product_id)->delete();

        Alert::message('User deleted successfully.', "Success");

        return redirect()->back();

    }
}

lrs/resources/views/action/create.blade.php
@extends('admin.app')

  
@section('content')
<a href="{{ route('action.index',['app_url' => base64_encode($app_url)]) }}">
    Back
</a>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="/actionList/{{$app_url}}" method="POST">
    @csrf
  
        <div class="form-group">
            <strong>Todo Action:</strong>
            <textarea class="form-control" style="height:150px" name="action" placeholder="Todo Action.."></textarea>
        </div>

        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>

 
   
</form>
@endsection

lrs/resources/views/action/edit.blade.php
@extends('admin.app')
   
@section('content')
    <a href="{{ route('action.index',['app_url' => base64_encode($product->app_url)]) }}">
        Back
    </a>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {{--  <form action="/actionList/{{$product->app_url}}" method="POST">  --}}
    <form action="/actionList/{{$product->app_url}}" method="POST">
        @csrf
       
        <input type='hidden' name="action_list" value="{{$product->action_list}}">
            <div class="form-group">
                <strong>Action:</strong>
                <textarea class="form-control" style="height:150px" name="action" placeholder="Action..">{{ $product->action }}</textarea>
            </div>

            <button type="submit" class="btn btn-primary btn-lg btn-block">Edit Action</button>

   
    </form>
@endsection

lrs/resources/views/action/index.blade.php
@extends('admin.app')

@section('content')

    <a href="/option/{{base64_encode($app_url)}}">
        Back
    </a>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table">
        <thead class="thead-dark">
            <tr>
                @php ($users = ['#','Action List','Todo','Action'])
                @foreach ($users as $user)
                  <th scope="col">{{$user}}</th>
                @endforeach
            </tr> 
        </thead>
        <tbody>
            @foreach ($products as $product)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $product->action_list }}</td>
                <td>{{ $product->action }}</td>
                <td>
                    <form action="{{ route('action.destroy',$product->id) }}" method="POST">
                        <input type='hidden' name="product_id" value="{{$product->id}}">
                        {{--  <a class="btn btn-info" href="{{ route('action.show',$product->id) }}">Show</a>  --}}
                        
                        <a class="btn btn-primary" href="{{ route('action.edit', base64_encode($product->id)) }}">Edit</a>
                     
                        @csrf
                        @method('DELETE')
                        
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody> 
    </table>
    {{--  <div class="pull-right">
            <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
        </div>  --}}
    {!! $products->links() !!}
    <a href="{{ route('action.create', ['app_url' => base64_encode($app_url)]) }}">
      <button type="button" class="btn btn-secondary btn-lg btn-block">Create ToDo</button>
    </a>
    <p></p> 
      
@endsection

lrs/resources/views/action/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 5.7</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

lrs/resources/views/action/show.blade.php
@extends('action.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('action.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $product->detail }}
            </div>
        </div>
    </div>
@endsection