lrs/routes/web.php
<?php

/* 
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//mail layouts
Route::get('/mailLayout', function () {
    return view('admin.mailContent');
});
Route::get('/', function () {
    return view('welcome');
});
//email content edit

Route::post('/mailContentUpdate', 'ProductController@mailContentUpdate');
//
Route::get('/mailEdit', 'ProductController@mailContentEdit')->name('mailEdit');
//login
Route::get('/user/{url}', function ($url) {
    $url = $url;
    return view('user.login',compact('url'));
})->name('home');

Route::get('/user_admin/{url}', function ($url) {
    $url = $url;
    return view('admin.login',compact('url'));
})->name('user_admin');
 
Route::get('mail', 'webAdminController@mail')->name('mail');
Route::post('webLogin', 'webController@webLogin')->name('login');
Route::post('adminLogin', 'webAdminController@adminLogin')->name('adminLogin');
//navigate
Route::get('/navigation/{navigate}/{uid}/{app_url}/{company}', 'webController@navigation')->name('navigation');
//device
Route::get('removeDevice/{device}', 'webController@removeDevice')->name('removeDevice');
//homeadmin
Route::get('/option/{app_url}', 'webAdminController@admimHome');
//
Route::post('changePassword', 'webController@changePassword')->name('changePassword');
Route::post('changePicture', 'webController@changePicture')->name('changePicture');

//create
Route::post('/userRegister', 'userController@userRegister');
Route::post('/actionList/{app_url}', 'scanActionListController@actionList');
//////crud
Route::resource('products', 'ProductController');
Route::resource('action','ActionController');
////excel
Route::get('export/{app_url}', 'ExcelController@export')->name('export');
Route::get('exportVisitorData/{app_url}', 'ExcelController@exportVisitorData')->name('exportVisitorData');
Route::get('importExportView', 'ExcelController@importExportView')->name('importExportView');
Route::get('importExhibitor', 'ExcelController@importExhibitor')->name('importExhibitor');
Route::post('import/{app_url}', 'ExcelController@import')->name('import');
Route::post('importE/{app_url}', 'ExcelController@importE')->name('importE');

////exhibitorsView
Route::get('exhibitorsView/{app_url}', 'ExcelController@exhibitorsView')->name('exhibitorsView');
// proIndex
Route::get('proIndex/{app_url}', 'ProductController@index')->name('proIndex');
//event
Route::get('event', 'appController@viewAll')->name('viewAll');
//admin
Route::get('/create', function () {
    return view('admin.create_app');
})->name('create');
//expired
Route::post('expired/{id}', 'appController@expired')->name('expired');
//edit view
Route::post('editEventView/{id}', 'appController@editEventView')->name('editEventView');
//edit
Route::post('editEvent/{id}', 'appController@editEvent')->name('editEvent');

lrs/resources/views/admin/action.blade.php
@extends('admin.app')

@section('content')
    <a href="/option/{{$products[0]->app_url}}">
        Back
    </a>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                @php ($users = ['#','Name','UID','Title','Interest','Company','Password','Position','Address','Email','User Name','Mobile','avatar','actions'])
                @foreach ($users as $user)
                  <th scope="col">{{$user}}</th>
                @endforeach
            </tr> 
        </thead>
        <tbody>
            @foreach ($products as $product)
            <tr>
                <td>{{ ++$i }}</td>

                @php ($users = [$product->name,$product->uid,$product->delegate,$product->interest,$product->company,$product->password,$product->position,$product->address,$product->email,$product->user_name,$product->mobile_no,$product->avatar])
                @foreach ($users as $value)
                <td>{{ $value }}</td>
                @endforeach
                <td>
                    <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                                        
                        <a style="width:80px" class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>
                    
                        @csrf
                        @method('DELETE')
                    
                        <button style="width:80px" type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    {!! $products->links() !!}
    <a href="{{ route('products.create') }}">
      <button type="button" class="btn btn-secondary btn-lg btn-block">Users CRUD</button>
    </a>
    <p></p> 
      
@endsection

lrs/resources/views/admin/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Lead Retrieval CMS Portal</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }

            .row {
                margin-top:20px;
                padding-top: 1rem;
            }

            .options {
                margin-top:20px;
            }
        </style>
    </head>
    <body>
        
        <div style="padding:3%" id="app" class="container-fluid">
                @include('admin.header')
                <div class="row">     
                    <main role="main" class="col-md-12">
                        @yield('content')
                    </main>
                </div>
            </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        @include('sweet::alert')
    </body>
    
</html>

lrs/resources/views/admin/create_app.blade.php
@extends('admin.app')

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="/api/app" method="POST" enctype="multipart/form-data" >
    {{ csrf_field() }}
  
    <a href="{{ route('viewAll') }}">
      <button type="button" class="btn btn-primary btn-lg btn-block">Exhibition Event CRUD </button>
    </a>
    <p></p> 
    @php
        $mytime = Carbon\Carbon::now();
        $today = $mytime->toDateTimeString();
    @endphp
    @php ($users = ['','rgb(241, 243, 244)',20,'arrow-forward','','black','white','black','',$today,$today,''])
    @php ($title = ['app_url','background_color','font_size','list_icon','main_title','title_color','btn_color','btn_text','user_id','start_date','end_date','footer_img'])
    @php ($label = ['Exhibition Short Form e.g-lrs/new','Exhibition App Background Color e.g-white/rgb(241, 243, 244)','Exhibition App Font Size e.g-20','Exhibition App Icon e.g-arrow-forward','Exhibition Name e.g-SEI Event Retrieval App','Exhibition App Title Color e.g-black','App Button Color e.g-white','App Button Text Color e.g-black','Exhibitor ID Short Form e.g-EX/NE (suggestion::First 2 character with your Exhibition Short Form)','Event Start Date','Event End Date','Footer logo'])

        <div class="form-group">
            
            @foreach ($users as $key => $item)
                 @if ($title[$key] == 'start_date' || $title[$key] == 'end_date')
                     <div class="form-group row">
                        <label for={{$title[$key]}} class="col-sm-2 col-form-label">{{$label[$key]}}</label>
                        <div class="col-sm-8">
                             <input required data-bv-notempty="true" maxlength="250" type="date" name="{{$title[$key]}}" value="{{ $item }}" class="form-control" placeholder="{{$label[$key]}}">
                        </div>
                    </div> 
                 @elseif($title[$key] == 'footer_img') 
                     <div class="form-group row">
                        <label for={{$title[$key]}} class="col-sm-2 col-form-label">{{$label[$key]}}</label>
                        <div class="col-sm-8">
                            <input required class="form-control" type="file" id="footer_img" name = "footer_img">
                        </div>
                    </div> 
                 @else
                     <div class="form-group row">
                        <label for={{$title[$key]}} class="col-sm-2 col-form-label">{{$label[$key]}}</label>
                        <div class="col-sm-8">
                             <input required data-bv-notempty="true" maxlength="250" type="text" name="{{$title[$key]}}" value="{{ $item }}" class="form-control" placeholder="{{$label[$key]}}">
                        </div>
                    </div> 
                 @endif
                
                
            @endforeach
            
        </div>  
        <button type="submit" class="btn btn-primary btn-lg btn-block">Create Event</button>
        <p></p> 
</form>
@endsection

lrs/resources/views/admin/header.blade.php
<nav style="background-color:white" class="navbar navbar-expand-md shadow navbar-light navbar-laravel fixed-top">
    <div class="container">
        <a style="color:#7f7f7f;font-size:18px" class="">
            Lead Retrieval CMS Portal Admin
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
 
            </ul>
                <!-- Authentication Links -->
                <a class="nav-link" href="/user_admin/lrs">{{ __('Login') }}</a>
                <a class="nav-link" href="/user_admin/lrs">{{ __('Logout') }}</a>
                {{-- <a class="nav-link" href="register">{{ __('Register') }}</a> --}}
            </ul>
        </div>
    </div>
</nav>

lrs/resources/views/admin/login.blade.php
@extends('admin.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"> 
                <div class="card-header">{{ __('Admin Login') }}</div>
                
                <div class="card-body">
                    <form method="POST" action="/adminLogin">
                        @csrf
                        <input type='hidden' name="app_url" value="{{$url}}">
                        <div class="form-group row">
                            <label for="email" class="col-sm-4 col-form-label text-md-right">{{ __('Admin ID') }}</label>

                            <div class="col-md-6">
                                <input id="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="user" value="{{ old('email') }}" required autofocus>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{--  <div class="form-group row">
                                <label for="app" class="col-sm-4 col-form-label text-md-right">{{ __('App Title') }}</label>
    
                                <div class="col-md-6">
                                    <input id="app" class="form-control{{ $errors->has('app') ? ' is-invalid' : '' }}" name="app_url" value="{{ old('app') }}" required autofocus>
    
                                    @if ($errors->has('app'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('app') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>  --}}

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

lrs/resources/views/admin/mailContent.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
 
        <title>Lead Retrieval CMS Mail</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

        <!-- Styles -->
        <style>
            
            .container {
                background: white;
                color: #636b6f;
                width:600;
           
            }
            .header{
                padding:10;
            }
            
            .headerIcon { 
                margin-left:1%;
                width: 7%; 
                float: left; 
                position: relative;
            }

            .headerText { 
                margin-top:10px;
                margin-left:18px;
                width: 35%; 
                float: left; 
                position: relative;
            }

            @media only screen and (max-width: 1000px) {
                .headerText { 
                    margin-top:0px;
                    width: 35%; 
                    float: left; 
                    position: relative;
                }
              }

            .text {
                
                color:#7f7f7f;
                font-size:80%;
                font-weight:bold;
            }
  
            .image{
                width: 100%;
            }
            .contentImage{
                width: 100%;
             
            }
            .contentText{
                font-family: 'Nunito', sans-serif;
                background: #f7f7f7;
                padding:20px;
                color:rgb(56, 55, 55);
                font-weight:bold;
            }
            .footer{
                padding:20px;
            }

            .footerLeft { 
                float: left; 
                position: relative;
            }

            .footerAdjust { 
                width: 50%; 
            }

            @media only screen and (max-width: 1000px) {
                .footerAdjust { 
                    width: 80%; 
                }
              }
  

            .footerRight { 
                
                float: left; 
                position: relative;
            }

            .footerRightAdjust { 
                width: 25%; 
            }

            @media only screen and (max-width: 1000px) {
                .footerRightAdjust { 
                    top:4vh;
                    width: 50%; 
                }
              }

            .footerBar{
                color:black;
            }

            .footerBarLeft { 
                width: 60%; 
                float: left; 
                position: relative;
            }

            .footerBarRight { 
                width: 13%; 
                float: right; 
                position: relative;
            }

            @media only screen and (max-width: 1000px) {
                .footerBarRight { 
                    width: 33%; 
                    float: right; 
                    position: relative;
                }
            }

        </style>
    </head>
    <body>
        <div class="container">
 
            <div class="header">
                <div class="headerIcon">
                    {{--  "http://18.224.94.233/"  --}}
                    @php
                        $header1 = $content->header_pic1;
                        $header2 = $content->header_pic2;
                        $content1 = $content->content_pic1;
                        $content2 = $content->content_pic2;
                        $url = "http://sei-app.com/";
                        $header_pic1 = "{$url}app{$header1}";
                        $header_pic2 = "{$url}app{$header2}";
                        $content_pic1 = "{$url}app{$content1}";
                        $content_pic2 = "{$url}app{$content2}";
                        
                    @endphp
                    <img src="{{ asset($header_pic1)}}" alt="img" title="img" width=45 height=45 data-auto-embed="attachment"/>
                </div>
               
                <div class="headerText text">
                   {{--  <p></p>  --}}
                    <text>{!! $content->date1 !!}</text><br>
                    <text>{!! $content->location1 !!}</text>
                </div>
     
                <div class="headerIcon">
                    <img src="{{ asset($header_pic2)}}" alt="img" title="img" width=45 height=45 data-auto-embed="attachment"/>
                </div>
          
                <div class="headerText text">
                    {{--  <p></p>  --}}
                    <text>{!! $content->date2 !!}</text><br>
                    <text>{!! $content->location2 !!}</text>
                </div>
            </div>
            
            <div class="imageContainer">
                <img class="image" src="{{ asset($content_pic1)}}" alt="img" width="100%" title="img" data-auto-embed="attachment"/>
            </div>
            <div class="contentText">
                <text>Dear {!! $user_name !!},</text>
                <br><br>
                <text>
                    {!! $content->content1 !!}
                </text>
            </div>

            <div class="imageContainer">
                <img class="contentImage" src="{{ asset($content_pic2)}}" alt="img" width="100%" title="img" data-auto-embed="attachment"/>
            </div>

            <div class="contentText">
                <text>
                    {!! $content->content2 !!}
                </text>
            </div>
           
            <div class="footer">
                <div class="footerLeft footerAdjust">
                    <div>More About Exhibition</div>
                    <br>
                    <text>
                        {!! $content->moreContent !!}
                    </text>
                    <br><br>
                    <text>{!! $content->CEO !!}, CEO</text>
                </div>
                <div class="footerRight footerRightAdjust">
                    <div>Keep Connected</div>
                    <br>
                    <div>
                        <text>{!! $content->company !!}</text>
                    </div>
             
                    <div>
                        <text>{!! $content->address !!}</text>
                    </div>
               
                    <div>
                        <text>{!! $content->email !!}</text>
                    </div>

                    <div>
                        <text>{!! $content->phone !!}</text>
                    </div>
                    
                </div>
                <div class="footerRight footerRightAdjust"> 
                    <div>Contact Info</div>
                    <br>
                    <div>
                        <a href={!! $content->facebook !!}><text>Like our Facebook</text></a>
                    </div>

                    <div>
                        <a href={!! $content->instagram !!}><text>Follow our Twitter</text></a>
                    </div>
   
                    <div>
                        <a href={!! $content->twitter !!}><text>Add our LinkedIn</text></a>
                    </div>

                    <div>
                        <a href={!! $content->LinkedIn !!}><text>Like our Facebook</text></a>
                    </div>
                    <br><br><br>
                </div>
                
            </div>
           
            <div class="footerBar">
                <div class="footerBarLeft">
                    &copy;2019 Lead Retrieval CMS System. All Right Reserved | Design by LevineC
                </div>
                
                <div class="footerBarRight">Term</div>
                <div class="footerBarRight">Privacy Policy</div>
                <div class="footerBarRight">Company Info</div>
            </div>
            
            
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    @include('sweet::alert')
</html>

lrs/resources/views/admin/option.blade.php
@extends('admin.app')

@section('content')
<div class="options">    
    <h4>{{$app_url}} . Welcome, Admin</h4>
    <div class="card">
      <div class="card-header">
       User Options
      </div> 
      <div class="card-body"> 
          {{--  base64_encode(  --}}
        <a href="{{ route('importExportView',['app_url' => base64_encode($app_url)]) }}">
            <button type="button" class="btn btn-primary btn-lg btn-block">Import or Export Users</button>
        </a> 
        <p></p> 
        {{-- <a href="{{ route('products.index',['app_url' => base64_encode($app_url)]) }}"> --}}
            
          <a href="/proIndex/{{base64_encode($app_url)}}">
          <button type="button" class="btn btn-light btn-lg btn-block">Users CRUD</button>
        </a>
        <p></p> 
        <a href="{{ route('importExhibitor',['app_url' => base64_encode($app_url)]) }}">
          <button type="button" class="btn btn-secondary btn-lg btn-block">Import or Export Visitors</button>
        </a> 
        <p></p> 
        <a href="/exhibitorsView/{{base64_encode($app_url)}}">
          <button type="button" class="btn btn-light btn-lg btn-block">View Visitors</button>
        </a> 
        <p></p> 
       
        <from>
          <a href="{{ route('action.index',['app_url' => base64_encode($app_url)]) }}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">Qualifier CRUD</button>
          </a>
        </from>
      </div>
    </div>
</div>
    
@endsection